on:
  push:

name: Release Builds
jobs:
  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: go get -d github.com/cretz/go-scrap && cd go-scrap/scrap-sys && cargo build --release && cd ../..
      - run: GOOS=darwin GORCH=amd64 go build -o build/screenshot-macos
      - run: ./build/screenshot-macos testing-macos
      - run: ./build/screenshot-macos testing-macos 2
      - run: ./build/screenshot-macos testing-macos 1
      - run: ./build/screenshot-macos testing-macos 0
      - run: ./build/screenshot-macos testing-macos invalid && ls -lah
      - run: ./build/screenshot-macos testing-macos 2 -d && sleep 0.5 && ls -lah && cat ss.log && sleep 4 && ls -lah && cat ss.log
      - {name: Store, uses: actions/upload-artifact@v2, with: {name: build, path: build, if-no-files-found: error}}
