on:
  push:
    tags:
      - '*'

name: Release Builds
jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          $env:GOOS = "windows"
          $env:GORCH = "amd64" 
          go build -o build/screenshot-windows.exe
          ./build/screenshot-windows.exe testing-windows
      - name: Windows release build for github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/screenshot-windows.exe,testing-windows.png'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true

  linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          lspci
          lshw -c display
          GOOS=linux
          GORCH=amd64
          go build -o build/screenshot-linux
          ./build/screenshot-linux testing-linux
      - name: linux release build for github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/screenshot-linux,testing-linux.png'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true

  macos:
    name: MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          GOOS=darwin
          GORCH=amd64
          go build -o build/screenshot-macos
          ./build/screenshot-macos testing-macos
      - name: macos release build for github
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/screenshot-macos,testing-macos.png'
          token: ${{ secrets.TOKEN }}
          allowUpdates: true
